[package]
name = "pantheon"
# siderunner
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = { git = "https://github.com/jonhoo/fantoccini/" }
# thirtyfour = { path = "../thirtyfour", feature = ["blocking"] }
tokio = { version = "0.2.0", features = [ "sync", "time" ] }
serde_json = "*"
serde = "*"
regex = "*"