[package]
name = "pantheon"
# siderunner
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.14.2"
# thirtyfour = { path = "../thirtyfour", feature = ["blocking"] }
tokio = { version = "0.2.0", features = [ "sync", "time" ] }
serde_json = "*"
serde = "*"
regex = "*"
async-trait = "0.1"
url = "*"

[dev-dependencies]
tokio = { version = "0.2.0", features = [ "full" ] }